name: molecule
channels:
  - rdkit
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - torchvision
  - cpuonly
  - pytorch
  - pandas
  - rdkit
  - tqdm
  - networkx
  - graphviz
  - python-graphviz

